// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bootstrap_cs_cpp
List bootstrap_cs_cpp(NumericMatrix psi, int B, double alpha, int B_pilot);
RcppExport SEXP _fixes_bootstrap_cs_cpp(SEXP psiSEXP, SEXP BSEXP, SEXP alphaSEXP, SEXP B_pilotSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type psi(psiSEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type B_pilot(B_pilotSEXP);
    rcpp_result_gen = Rcpp::wrap(bootstrap_cs_cpp(psi, B, alpha, B_pilot));
    return rcpp_result_gen;
END_RCPP
}
// compute_att_gt_cpp
Rcpp::DataFrame compute_att_gt_cpp(Rcpp::IntegerVector unit_id, Rcpp::IntegerVector time_id, Rcpp::NumericVector outcome, Rcpp::IntegerVector cohort, Rcpp::IntegerVector cohorts, Rcpp::IntegerVector all_times, std::string control_group, int anticipation);
RcppExport SEXP _fixes_compute_att_gt_cpp(SEXP unit_idSEXP, SEXP time_idSEXP, SEXP outcomeSEXP, SEXP cohortSEXP, SEXP cohortsSEXP, SEXP all_timesSEXP, SEXP control_groupSEXP, SEXP anticipationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type unit_id(unit_idSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type time_id(time_idSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type outcome(outcomeSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type cohort(cohortSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type cohorts(cohortsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type all_times(all_timesSEXP);
    Rcpp::traits::input_parameter< std::string >::type control_group(control_groupSEXP);
    Rcpp::traits::input_parameter< int >::type anticipation(anticipationSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_att_gt_cpp(unit_id, time_id, outcome, cohort, cohorts, all_times, control_group, anticipation));
    return rcpp_result_gen;
END_RCPP
}
// build_cov_interactions_cpp
NumericMatrix build_cov_interactions_cpp(NumericMatrix cov_mat, IntegerMatrix ind_mat, IntegerVector group_key);
RcppExport SEXP _fixes_build_cov_interactions_cpp(SEXP cov_matSEXP, SEXP ind_matSEXP, SEXP group_keySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type cov_mat(cov_matSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type ind_mat(ind_matSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group_key(group_keySEXP);
    rcpp_result_gen = Rcpp::wrap(build_cov_interactions_cpp(cov_mat, ind_mat, group_key));
    return rcpp_result_gen;
END_RCPP
}
// build_indicator_matrix_cpp
IntegerMatrix build_indicator_matrix_cpp(IntegerVector cohort_id, IntegerVector time_id, IntegerVector gs_g, IntegerVector gs_s);
RcppExport SEXP _fixes_build_indicator_matrix_cpp(SEXP cohort_idSEXP, SEXP time_idSEXP, SEXP gs_gSEXP, SEXP gs_sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type cohort_id(cohort_idSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type time_id(time_idSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type gs_g(gs_gSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type gs_s(gs_sSEXP);
    rcpp_result_gen = Rcpp::wrap(build_indicator_matrix_cpp(cohort_id, time_id, gs_g, gs_s));
    return rcpp_result_gen;
END_RCPP
}
// aggregate_iw_cpp
DataFrame aggregate_iw_cpp(NumericVector estimates, IntegerVector l_vals, IntegerVector cohort_vals, IntegerVector idx_in_V, NumericMatrix V_full_r, IntegerVector unique_l, IntegerVector cs_keys, IntegerVector cs_vals, int min_t, int max_t);
RcppExport SEXP _fixes_aggregate_iw_cpp(SEXP estimatesSEXP, SEXP l_valsSEXP, SEXP cohort_valsSEXP, SEXP idx_in_VSEXP, SEXP V_full_rSEXP, SEXP unique_lSEXP, SEXP cs_keysSEXP, SEXP cs_valsSEXP, SEXP min_tSEXP, SEXP max_tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type estimates(estimatesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type l_vals(l_valsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cohort_vals(cohort_valsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type idx_in_V(idx_in_VSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type V_full_r(V_full_rSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type unique_l(unique_lSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cs_keys(cs_keysSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cs_vals(cs_valsSEXP);
    Rcpp::traits::input_parameter< int >::type min_t(min_tSEXP);
    Rcpp::traits::input_parameter< int >::type max_t(max_tSEXP);
    rcpp_result_gen = Rcpp::wrap(aggregate_iw_cpp(estimates, l_vals, cohort_vals, idx_in_V, V_full_r, unique_l, cs_keys, cs_vals, min_t, max_t));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fixes_bootstrap_cs_cpp", (DL_FUNC) &_fixes_bootstrap_cs_cpp, 4},
    {"_fixes_compute_att_gt_cpp", (DL_FUNC) &_fixes_compute_att_gt_cpp, 8},
    {"_fixes_build_cov_interactions_cpp", (DL_FUNC) &_fixes_build_cov_interactions_cpp, 3},
    {"_fixes_build_indicator_matrix_cpp", (DL_FUNC) &_fixes_build_indicator_matrix_cpp, 4},
    {"_fixes_aggregate_iw_cpp", (DL_FUNC) &_fixes_aggregate_iw_cpp, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_fixes(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
