# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Core of the Callaway-Sant'Anna (2021) multiplier bootstrap (Algorithm 1)
#'
#' Performs two-stage multiplier bootstrap in C++ using R's RNG stream:
#' \enumerate{
#'   \item Pilot stage (B_pilot draws): estimates per-parameter dispersion
#'     \eqn{\hat\sigma_{1/2}} via normalised IQR of
#'     \eqn{\sqrt{n}\,\bar{V}\psi_{g,t}}.
#'   \item Main stage (B draws): computes the maximum studentised t-statistic
#'     per draw and returns the (1-alpha) quantile as the simultaneous
#'     critical value.
#' }
#'
#' Uses \code{R::runif(0,1)} for Mammen weight generation, so the output is
#' identical to the pure-R implementation when the same \code{set.seed()} is
#' applied before calling either version.
#'
#' @param psi     Numeric matrix (n_units × n_gt) of unit-level influence
#'   functions (output of \code{.compute_influence_cs()}).
#' @param B       Number of main bootstrap draws.
#' @param alpha   Significance level for the simultaneous band (e.g. 0.05).
#' @param B_pilot Number of pilot draws for \eqn{\hat\sigma_{1/2}} estimation
#'   (default 199).
#'
#' @return Named list with:
#' \describe{
#'   \item{\code{c_hat}}{Scalar simultaneous critical value.}
#'   \item{\code{margin}}{\code{n_gt}-vector: per-parameter CI half-widths
#'     = \code{c_hat * sigma_half / sqrt(n)}.}
#'   \item{\code{sigma_half}}{\code{n_gt}-vector: estimated
#'     \eqn{\hat\sigma_{1/2}} values (IQR-based).}
#' }
#'
#' @noRd
bootstrap_cs_cpp <- function(psi, B, alpha, B_pilot) {
    .Call(`_fixes_bootstrap_cs_cpp`, psi, B, alpha, B_pilot)
}

compute_att_gt_cpp <- function(unit_id, time_id, outcome, cohort, cohorts, all_times, control_group, anticipation = 0L) {
    .Call(`_fixes_compute_att_gt_cpp`, unit_id, time_id, outcome, cohort, cohorts, all_times, control_group, anticipation)
}

#' Build covariate-interaction matrix with group-level demeaning
#'
#' For each unique non-missing, non-zero value in \code{group_key}, the
#' covariates in that group are centred on their within-group column means.
#' The result is then multiplied element-wise with the 0/1 indicator matrix
#' to produce the N × (K × p) covariate-interaction matrix used by the TWM
#' and FLEX estimators (Wooldridge 2025, Procedure 5.1; Deb et al. 2024,
#' Eq. 2.11 / 3.1).
#'
#' \strong{TWM usage:} pass \code{group_key = as.integer(timing_vec)};
#' NA values (never-treated) are skipped and produce zero rows.
#'
#' \strong{FLEX usage:} pre-compute a cell key in R:
#' \preformatted{
#'   cohort_chr <- ifelse(is.na(cohort_of_obs), "NA",
#'                        as.character(cohort_of_obs))
#'   cell_key   <- as.integer(factor(paste(cohort_chr, time_id, sep="_")))
#'   cell_key[is.na(cohort_of_obs)] <- NA_integer_
#' }
#' This gives one unique integer per (cohort, calendar-time) cell.
#'
#' @param cov_mat    N × p numeric matrix of raw covariate values.
#' @param ind_mat    N × K integer matrix of 0/1 treatment-cell indicators
#'   (output of \code{build_indicator_matrix_cpp()}).
#' @param group_key  Integer vector of length N: group identifier for
#'   centring.  \code{NA_integer_} or \code{0} → row is excluded from all
#'   group means and contributes 0 to the output.
#'
#' @return N × (K × p) numeric matrix.  Column order: for each covariate j
#'   (j = 0 … p-1), the K columns \code{ind_mat[,k] * x_centred[,j]}
#'   for k = 0 … K-1 are contiguous.  Column names are set by the R caller.
#'
#' @noRd
build_cov_interactions_cpp <- function(cov_mat, ind_mat, group_key) {
    .Call(`_fixes_build_cov_interactions_cpp`, cov_mat, ind_mat, group_key)
}

#' Build cohort-by-calendar-time indicator matrix
#'
#' For each (g, s) pair, fills column k of the output matrix with 1 for rows
#' where \code{cohort_id[i] == gs_g[k] && time_id[i] == gs_s[k]}, and 0
#' elsewhere.  \code{NA_integer_} values in \code{cohort_id} (never-treated
#' units) are treated as no-cohort and always produce 0.
#'
#' This is a shared utility used by the SA, TWM, and FLEX estimators to
#' replace the equivalent R nested for-loop, avoiding repeated vector
#' allocation and R overhead per column.
#'
#' @param cohort_id Integer vector (length N): cohort assignment per row.
#'   Pass \code{NA_integer_} for never-treated observations.
#'   For FLEX, pass the cohort of each observation's group
#'   (pre-computed as \code{timing_by_group[as.character(group_vec)]}).
#' @param time_id Integer vector (length N): calendar time per row.
#' @param gs_g Integer vector (length K): cohort value for each (g,s) pair.
#' @param gs_s Integer vector (length K): calendar time for each (g,s) pair.
#'
#' @return An N × K integer matrix with 0/1 entries.
#'
#' @noRd
build_indicator_matrix_cpp <- function(cohort_id, time_id, gs_g, gs_s) {
    .Call(`_fixes_build_indicator_matrix_cpp`, cohort_id, time_id, gs_g, gs_s)
}

#' Interaction-weighted event-study aggregation with full VCOV
#'
#' Computes the cohort-size-weighted event-study estimate and its standard
#' error for each unique event time \eqn{\ell} in \code{unique_l}:
#' \deqn{\hat\theta(\ell) = \sum_g w_{g,\ell} \hat\tau_{g,g+\ell}}
#' \deqn{\widehat{SE}^2(\hat\theta(\ell)) =
#'   \mathbf{w}_\ell^\top \Sigma_\ell \mathbf{w}_\ell}
#' where \eqn{\Sigma_\ell} is the VCOV sub-block for all cohorts at \eqn{\ell}
#' and \eqn{w_{g,\ell} = n_g / \sum_{g' : g'+\ell \in [t_{\min}, t_{\max}]} n_{g'}}.
#'
#' This is a shared utility replacing the equivalent R loop in the SA, TWM,
#' and FLEX estimators, using RcppArmadillo for the quadratic form.
#'
#' @param estimates Numeric vector (length K): \eqn{\hat\tau_{g,s}} estimates.
#' @param l_vals Integer vector (length K): relative time \eqn{\ell = s - g}.
#' @param cohort_vals Integer vector (length K): cohort \eqn{g} for each cell.
#' @param idx_in_V Integer vector (length K): 0-based row/column index into
#'   \code{V_full_r}.  Pass \code{-1L} for cells not found in the VCOV.
#' @param V_full_r Numeric matrix: full VCOV from the regression.
#' @param unique_l Sorted integer vector: all unique event times to aggregate.
#' @param cs_keys Integer vector: cohort values (one per cohort).
#' @param cs_vals Integer vector: cohort sizes corresponding to \code{cs_keys}.
#' @param min_t,max_t Integer: range of observed calendar times.
#'
#' @return A data.frame with columns \code{relative_time}, \code{estimate},
#'   \code{std_error}, one row per valid event time.
#'
#' @noRd
aggregate_iw_cpp <- function(estimates, l_vals, cohort_vals, idx_in_V, V_full_r, unique_l, cs_keys, cs_vals, min_t, max_t) {
    .Call(`_fixes_aggregate_iw_cpp`, estimates, l_vals, cohort_vals, idx_in_V, V_full_r, unique_l, cs_keys, cs_vals, min_t, max_t)
}

