# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Core of the Callaway-Sant'Anna (2021) multiplier bootstrap (Algorithm 1)
#'
#' Performs two-stage multiplier bootstrap in C++ using R's RNG stream:
#' \enumerate{
#'   \item Pilot stage (B_pilot draws): estimates per-parameter dispersion
#'     \eqn{\hat\sigma_{1/2}} via normalised IQR of
#'     \eqn{\sqrt{n}\,\bar{V}\psi_{g,t}}.
#'   \item Main stage (B draws): computes the maximum studentised t-statistic
#'     per draw and returns the (1-alpha) quantile as the simultaneous
#'     critical value.
#' }
#'
#' Uses \code{R::runif(0,1)} for Mammen weight generation, so the output is
#' identical to the pure-R implementation when the same \code{set.seed()} is
#' applied before calling either version.
#'
#' @param psi     Numeric matrix (n_units × n_gt) of unit-level influence
#'   functions (output of \code{.compute_influence_cs()}).
#' @param B       Number of main bootstrap draws.
#' @param alpha   Significance level for the simultaneous band (e.g. 0.05).
#' @param B_pilot Number of pilot draws for \eqn{\hat\sigma_{1/2}} estimation
#'   (default 199).
#'
#' @return Named list with:
#' \describe{
#'   \item{\code{c_hat}}{Scalar simultaneous critical value.}
#'   \item{\code{margin}}{\code{n_gt}-vector: per-parameter CI half-widths
#'     = \code{c_hat * sigma_half / sqrt(n)}.}
#'   \item{\code{sigma_half}}{\code{n_gt}-vector: estimated
#'     \eqn{\hat\sigma_{1/2}} values (IQR-based).}
#' }
#'
#' @noRd
bootstrap_cs_cpp <- function(psi, B, alpha, B_pilot) {
    .Call(`_fixes_bootstrap_cs_cpp`, psi, B, alpha, B_pilot)
}

compute_att_gt_cpp <- function(unit_id, time_id, outcome, cohort, cohorts, all_times, control_group, anticipation = 0L) {
    .Call(`_fixes_compute_att_gt_cpp`, unit_id, time_id, outcome, cohort, cohorts, all_times, control_group, anticipation)
}

#' Build covariate-interaction matrix with group-level demeaning
#'
#' For each unique non-missing, non-zero value in \code{group_key}, the
#' covariates in that group are centred on their within-group column means.
#' The result is then multiplied element-wise with the 0/1 indicator matrix
#' to produce the N × (K × p) covariate-interaction matrix used by the TWM
#' and FLEX estimators (Wooldridge 2025, Procedure 5.1; Deb et al. 2024,
#' Eq. 2.11 / 3.1).
#'
#' \strong{TWM usage:} pass \code{group_key = as.integer(timing_vec)};
#' NA values (never-treated) are skipped and produce zero rows.
#'
#' \strong{FLEX usage:} pre-compute a cell key in R:
#' \preformatted{
#'   cohort_chr <- ifelse(is.na(cohort_of_obs), "NA",
#'                        as.character(cohort_of_obs))
#'   cell_key   <- as.integer(factor(paste(cohort_chr, time_id, sep="_")))
#'   cell_key[is.na(cohort_of_obs)] <- NA_integer_
#' }
#' This gives one unique integer per (cohort, calendar-time) cell.
#'
#' @param cov_mat    N × p numeric matrix of raw covariate values.
#' @param ind_mat    N × K integer matrix of 0/1 treatment-cell indicators
#'   (output of \code{build_indicator_matrix_cpp()}).
#' @param group_key  Integer vector of length N: group identifier for
#'   centring.  \code{NA_integer_} or \code{0} → row is excluded from all
#'   group means and contributes 0 to the output.
#'
#' @return N × (K × p) numeric matrix.  Column order: for each covariate j
#'   (j = 0 … p-1), the K columns \code{ind_mat[,k] * x_centred[,j]}
#'   for k = 0 … K-1 are contiguous.  Column names are set by the R caller.
#'
#' @noRd
build_cov_interactions_cpp <- function(cov_mat, ind_mat, group_key) {
    .Call(`_fixes_build_cov_interactions_cpp`, cov_mat, ind_mat, group_key)
}

#' K-way fixed-effects demeaning by alternating projections
#'
#' Demeans each column of \code{M} with respect to all fixed-effect
#' dimensions simultaneously (Gauss-Seidel sweeps over the FE dimensions
#' until the largest subtracted group mean falls below \code{tol} times the
#' column scale). With a single FE dimension one sweep is exact.
#'
#' Columns are independent, so they are distributed over OpenMP threads;
#' the per-column arithmetic is unchanged by the thread count, making the
#' result bit-identical for any \code{nthreads}.
#'
#' \code{fe_ids} must contain dense 0-based level indices per dimension and
#' the rows must already form the final estimation sample (NA rows and
#' singleton FE levels removed by the caller, see \code{.fit_fe_ols()}).
#'
#' @param M Numeric matrix (N x C): columns to demean (outcome + regressors).
#' @param fe_ids Integer matrix (N x Q): 0-based FE level index per dimension.
#' @param n_levels Integer vector (length Q): number of levels per dimension.
#' @param tol Relative convergence tolerance on subtracted group means.
#' @param max_iter Maximum number of full sweeps per column.
#' @param nthreads Number of OpenMP threads (ignored without OpenMP).
#'
#' @return A list with \code{M} (demeaned copy) and \code{converged}.
#'
#' @noRd
demean_kway_cpp <- function(M, fe_ids, n_levels, tol, max_iter, nthreads) {
    .Call(`_fixes_demean_kway_cpp`, M, fe_ids, n_levels, tol, max_iter, nthreads)
}

#' Sequential Cholesky with keep-first column dropping
#'
#' In-place C++ counterpart of the previous R implementation in
#' \code{.chol_seq_drop()}: columns of \code{XtX} are processed left to
#' right; a column is dropped when its diagonal is numerically zero
#' relative to \code{d_pre} (absorbed by the FEs) or when its residual
#' diagonal after projecting on the previously kept columns falls below
#' \code{tol} times its own diagonal (collinear with kept columns).
#'
#' @param XtX Symmetric cross-product matrix (K x K).
#' @param d_pre Numeric vector (length K): pre-demeaning column scales.
#' @param tol Relative drop tolerance.
#'
#' @return A list with \code{kept} (1-based indices of kept columns) and
#'   \code{R} (upper-triangular Cholesky factor of the kept block).
#'
#' @noRd
chol_seq_drop_cpp <- function(XtX, d_pre, tol) {
    .Call(`_fixes_chol_seq_drop_cpp`, XtX, d_pre, tol)
}

#' Symmetric cross product M'M with OpenMP column parallelism
#'
#' Computes \code{crossprod(M)} with a fixed per-entry accumulation order,
#' so the result is bit-identical for any thread count. Columns of the
#' output are distributed over threads; the inner accumulation processes
#' the left columns in blocks of four to reduce memory traffic.
#'
#' @param M Numeric matrix (N x C).
#' @param nthreads Number of OpenMP threads (ignored without OpenMP).
#'
#' @return C x C numeric matrix M'M (no dimnames).
#'
#' @noRd
crossprod_omp_cpp <- function(M, nthreads) {
    .Call(`_fixes_crossprod_omp_cpp`, M, nthreads)
}

#' Alternating-projections solver for a two-way fixed-effects model
#'
#' Solves \eqn{Y = \alpha_{unit} + \beta_{time} + \varepsilon} by
#' Gauss-Seidel alternating means with Irons-Tuck acceleration on the
#' time-FE vector.
#'
#' The estimation sample must already exclude NA outcomes and singleton
#' FE levels, and \code{unit_id}/\code{time_id} must be dense 0-based
#' indices (see \code{.solve_fe_2way()}, which prepares both).
#'
#' Only the sums \eqn{\alpha_i + \beta_t} are identified; no normalization
#' is applied, so callers must always use \code{alpha} and \code{beta}
#' jointly.
#'
#' @param y Numeric outcome vector (length N, no NAs).
#' @param unit_id Integer vector (length N): 0-based unit index per row.
#' @param time_id Integer vector (length N): 0-based time index per row.
#' @param n_unit Number of unit levels.
#' @param n_time Number of time levels.
#' @param tol Relative convergence tolerance on the time-FE vector.
#' @param max_iter Maximum number of Gauss-Seidel sweeps.
#'
#' @return A list with \code{alpha} (length \code{n_unit}), \code{beta}
#'   (length \code{n_time}), \code{iterations}, \code{converged}, and
#'   \code{last_delta} (the last sweep-to-sweep change).
#'
#' @noRd
solve_fe_2way_cpp <- function(y, unit_id, time_id, n_unit, n_time, tol, max_iter) {
    .Call(`_fixes_solve_fe_2way_cpp`, y, unit_id, time_id, n_unit, n_time, tol, max_iter)
}

#' Build cohort-by-calendar-time indicator matrix
#'
#' For each (g, s) pair, fills column k of the output matrix with 1 for rows
#' where \code{cohort_id[i] == gs_g[k] && time_id[i] == gs_s[k]}, and 0
#' elsewhere.  \code{NA_integer_} values in \code{cohort_id} (never-treated
#' units) are treated as no-cohort and always produce 0.
#'
#' This is a shared utility used by the SA, TWM, and FLEX estimators to
#' replace the equivalent R nested for-loop, avoiding repeated vector
#' allocation and R overhead per column.
#'
#' @param cohort_id Integer vector (length N): cohort assignment per row.
#'   Pass \code{NA_integer_} for never-treated observations.
#'   For FLEX, pass the cohort of each observation's group
#'   (pre-computed as \code{timing_by_group[as.character(group_vec)]}).
#' @param time_id Integer vector (length N): calendar time per row.
#' @param gs_g Integer vector (length K): cohort value for each (g,s) pair.
#' @param gs_s Integer vector (length K): calendar time for each (g,s) pair.
#'
#' @return An N × K integer matrix with 0/1 entries.
#'
#' @noRd
build_indicator_matrix_cpp <- function(cohort_id, time_id, gs_g, gs_s) {
    .Call(`_fixes_build_indicator_matrix_cpp`, cohort_id, time_id, gs_g, gs_s)
}

#' Interaction-weighted event-study aggregation with full VCOV
#'
#' Computes the cohort-size-weighted event-study estimate and its standard
#' error for each unique event time \eqn{\ell} in \code{unique_l}:
#' \deqn{\hat\theta(\ell) = \sum_g w_{g,\ell} \hat\tau_{g,g+\ell}}
#' \deqn{\widehat{SE}^2(\hat\theta(\ell)) =
#'   \mathbf{w}_\ell^\top \Sigma_\ell \mathbf{w}_\ell}
#' where \eqn{\Sigma_\ell} is the VCOV sub-block for all cohorts at \eqn{\ell}
#' and \eqn{w_{g,\ell} = n_g / \sum_{g' : g'+\ell \in [t_{\min}, t_{\max}]} n_{g'}}.
#'
#' This is a shared utility replacing the equivalent R loop in the SA, TWM,
#' and FLEX estimators, using RcppArmadillo for the quadratic form.
#'
#' @param estimates Numeric vector (length K): \eqn{\hat\tau_{g,s}} estimates.
#' @param l_vals Integer vector (length K): relative time \eqn{\ell = s - g}.
#' @param cohort_vals Integer vector (length K): cohort \eqn{g} for each cell.
#' @param idx_in_V Integer vector (length K): 0-based row/column index into
#'   \code{V_full_r}.  Pass \code{-1L} for cells not found in the VCOV.
#' @param V_full_r Numeric matrix: full VCOV from the regression.
#' @param unique_l Sorted integer vector: all unique event times to aggregate.
#' @param cs_keys Integer vector: cohort values (one per cohort).
#' @param cs_vals Integer vector: cohort sizes corresponding to \code{cs_keys}.
#' @param min_t,max_t Integer: range of observed calendar times.
#'
#' @return A data.frame with columns \code{relative_time}, \code{estimate},
#'   \code{std_error}, one row per valid event time.
#'
#' @noRd
aggregate_iw_cpp <- function(estimates, l_vals, cohort_vals, idx_in_V, V_full_r, unique_l, cs_keys, cs_vals, min_t, max_t) {
    .Call(`_fixes_aggregate_iw_cpp`, estimates, l_vals, cohort_vals, idx_in_V, V_full_r, unique_l, cs_keys, cs_vals, min_t, max_t)
}

